### ISSUE TITLE
Inquiry Regarding Code Open-Source Plan and Mentioned Benchmarks for Construct-VL

### ISSUE THREAD

**Issue by euminds** [jamessealesmith/ConStruct-VL#1]
Hello，

I have been following the progress of continual learning and I am particularly interested in your excellent work, like CODA-Prompt. And I believe that [ConStruct-VL] is the next research stage of continual learning. I hope exploring its implementation and evaluating its performance through the mentioned benchmarks.  Thank you very much for your attention to this matter.

Best,
Euminds

**Comment by jamessealesmith** [comment]
Hi euminds!

Thank you very much for your interest in our work! We are incredibly sorry for the delay (there was a timing logistics issue for code release as this work was done during an internship by the first author). We will release the code very soon - ideally by the end of the month.

Best,
Authors

**Comment by euminds** [comment]
> Hi euminds!
> 
> Thank you very much for your interest in our work! We are incredibly sorry for the delay (there was a timing logistics issue for code release as this work was done during an internship by the first author). We will release the code very soon - ideally by the end of the month.
> 
> Best, Authors

Hi jamessealesmith!

I work for a project involving the attributes of a human and add them in a diffusion model. I believe that [ConStruct-VL] is helpful for the current work. it may like https://czhang0528.github.io/iti-gen. Thank you very much for your attention to this matter.

Best,
Euminds
